spring.application.name=courses
spring.data.mongodb.database=courses_app
# spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.uri=

spring.mail.username=
spring.mail.password=
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# spring.cache.type=simple

discount.value=10


# braintree
braintree.environment = sandbox
braintree.merchantId = 
braintree.privateKey = 
braintree.publicKey = 

# paymob
card.integration.id = 4599923
paymob.api.publicKey = 
paymob.api.secretkey = 
wallet.integration.id = 

# paypal 
paypal.mode=sandbox
paypal.client.id= 
paypal.client.secret= 


# Enable HTTPS (SSL) in Spring Boot
server.port=8080
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/root/keystore.p12
server.ssl.key-store-password=
server.ssl.key-alias=tomcat
